services:
  web:
    image: php:apache
    container_name: php_apache
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    build:
      context: .
      dockerfile: Dockerfile

  php_extensions:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www/html

